[build]
appDir = "."

providers = ["python"]

[phases.setup]
nixPkgs = [
  "gcc",
  "libxml2",
  "libxslt",
  "sqlite",
  "pkg-config"
]

[phases.start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"