providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311",  
  "gcc",
  "libxml2",
  "libxslt",
  "sqlite",
  "pkg-config"
]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"