[build]
appDir = "."

[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "libxml2",
  "libxslt",
  "sqlite",
  "pkg-config"
]

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn api.main:app --host 0.0.0.0 --port $PORT'